-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Enum.Follow_connection_select_column exposing (Follow_connection_select_column(..), decoder, fromString, list, toString)

import Json.Decode as Decode exposing (Decoder)


{-| select columns of table "follow\_connection"

  - Created - column name
  - Followed\_user\_id - column name
  - Follower\_id - column name
  - Id - column name

-}
type Follow_connection_select_column
    = Created
    | Followed_user_id
    | Follower_id
    | Id


list : List Follow_connection_select_column
list =
    [ Created, Followed_user_id, Follower_id, Id ]


decoder : Decoder Follow_connection_select_column
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "created" ->
                        Decode.succeed Created

                    "followed_user_id" ->
                        Decode.succeed Followed_user_id

                    "follower_id" ->
                        Decode.succeed Follower_id

                    "id" ->
                        Decode.succeed Id

                    _ ->
                        Decode.fail ("Invalid Follow_connection_select_column type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Follow_connection_select_column -> String
toString enum =
    case enum of
        Created ->
            "created"

        Followed_user_id ->
            "followed_user_id"

        Follower_id ->
            "follower_id"

        Id ->
            "id"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Follow_connection_select_column
fromString enumString =
    case enumString of
        "created" ->
            Just Created

        "followed_user_id" ->
            Just Followed_user_id

        "follower_id" ->
            Just Follower_id

        "id" ->
            Just Id

        _ ->
            Nothing
