-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Enum.Follow_connection_constraint exposing (Follow_connection_constraint(..), decoder, fromString, list, toString)

import Json.Decode as Decode exposing (Decoder)


{-| unique or primary key constraints on table "follow\_connection"

  - Follow\_connection\_pkey - unique or primary key constraint

-}
type Follow_connection_constraint
    = Follow_connection_pkey


list : List Follow_connection_constraint
list =
    [ Follow_connection_pkey ]


decoder : Decoder Follow_connection_constraint
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "follow_connection_pkey" ->
                        Decode.succeed Follow_connection_pkey

                    _ ->
                        Decode.fail ("Invalid Follow_connection_constraint type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Follow_connection_constraint -> String
toString enum =
    case enum of
        Follow_connection_pkey ->
            "follow_connection_pkey"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Follow_connection_constraint
fromString enumString =
    case enumString of
        "follow_connection_pkey" ->
            Just Follow_connection_pkey

        _ ->
            Nothing
