-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Object.Follow_connection exposing (created, followed_user, followed_user_id, follower, follower_id, id)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Hasura.InputObject
import Hasura.Interface
import Hasura.Object
import Hasura.Scalar
import Hasura.ScalarCodecs
import Hasura.Union
import Json.Decode as Decode


created : SelectionSet Hasura.ScalarCodecs.Timestamptz Hasura.Object.Follow_connection
created =
    Object.selectionForField "ScalarCodecs.Timestamptz" "created" [] (Hasura.ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecTimestamptz |> .decoder)


{-| An object relationship
-}
followed_user : SelectionSet decodesTo Hasura.Object.User -> SelectionSet decodesTo Hasura.Object.Follow_connection
followed_user object_ =
    Object.selectionForCompositeField "followed_user" [] object_ identity


followed_user_id : SelectionSet Hasura.ScalarCodecs.Uuid Hasura.Object.Follow_connection
followed_user_id =
    Object.selectionForField "ScalarCodecs.Uuid" "followed_user_id" [] (Hasura.ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


{-| An object relationship
-}
follower : SelectionSet decodesTo Hasura.Object.User -> SelectionSet decodesTo Hasura.Object.Follow_connection
follower object_ =
    Object.selectionForCompositeField "follower" [] object_ identity


follower_id : SelectionSet Hasura.ScalarCodecs.Uuid Hasura.Object.Follow_connection
follower_id =
    Object.selectionForField "ScalarCodecs.Uuid" "follower_id" [] (Hasura.ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


id : SelectionSet Hasura.ScalarCodecs.Uuid Hasura.Object.Follow_connection
id =
    Object.selectionForField "ScalarCodecs.Uuid" "id" [] (Hasura.ScalarCodecs.codecs |> Hasura.Scalar.unwrapCodecs |> .codecUuid |> .decoder)
