-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Object exposing (Follow_connection(..), Follow_connection_aggregate(..), Follow_connection_aggregate_fields(..), Follow_connection_max_fields(..), Follow_connection_min_fields(..), Follow_connection_mutation_response(..), User(..), User_aggregate(..), User_aggregate_fields(..), User_avg_fields(..), User_max_fields(..), User_min_fields(..), User_mutation_response(..), User_stddev_fields(..), User_stddev_pop_fields(..), User_stddev_samp_fields(..), User_sum_fields(..), User_var_pop_fields(..), User_var_samp_fields(..), User_variance_fields(..))


type Follow_connection
    = Follow_connection


type Follow_connection_aggregate
    = Follow_connection_aggregate


type Follow_connection_aggregate_fields
    = Follow_connection_aggregate_fields


type Follow_connection_max_fields
    = Follow_connection_max_fields


type Follow_connection_min_fields
    = Follow_connection_min_fields


type Follow_connection_mutation_response
    = Follow_connection_mutation_response


type User
    = User


type User_aggregate
    = User_aggregate


type User_aggregate_fields
    = User_aggregate_fields


type User_avg_fields
    = User_avg_fields


type User_max_fields
    = User_max_fields


type User_min_fields
    = User_min_fields


type User_mutation_response
    = User_mutation_response


type User_stddev_fields
    = User_stddev_fields


type User_stddev_pop_fields
    = User_stddev_pop_fields


type User_stddev_samp_fields
    = User_stddev_samp_fields


type User_sum_fields
    = User_sum_fields


type User_var_pop_fields
    = User_var_pop_fields


type User_var_samp_fields
    = User_var_samp_fields


type User_variance_fields
    = User_variance_fields
